//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankconsumerdetail
    {
        public int Id { get; set; }
        public string BankId { get; set; }
        public string ConsumerId { get; set; }
        public string ConsumerPhone { get; set; }
    }
}
