//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_master
    {
        public int cityid { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> countryid { get; set; }
        public string City { get; set; }
    }
}
