//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int com_id { get; set; }
        public string rest_id { get; set; }
        public string comments { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
