//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumergroup
    {
        public int id { get; set; }
        public string MerchantId { get; set; }
        public string ConsumerUserId { get; set; }
        public string GroupName { get; set; }
    }
}
