//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        public int enq_id { get; set; }
        public string enq_bname { get; set; }
        public string enq_owner { get; set; }
        public string enq_email { get; set; }
        public string enq_cell { get; set; }
        public string assign_to { get; set; }
        public System.DateTime creation_date { get; set; }
        public string state { get; set; }
        public string city { get; set; }
    }
}
