//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int MenuId { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public string ItemDiscription { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> PackagingCharges { get; set; }
        public Nullable<double> DeliveryCharge { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
