//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int report_id { get; set; }
        public string branch { get; set; }
        public System.DateTime date { get; set; }
        public string opening_balance { get; set; }
        public string compsale { get; set; }
        public string extsale { get; set; }
        public string loan { get; set; }
        public string rent { get; set; }
        public string lbr { get; set; }
        public string pigmy { get; set; }
        public string lbwf { get; set; }
        public string shopexp { get; set; }
        public string braw { get; set; }
        public string otherexp { get; set; }
        public string personalexp { get; set; }
        public string paid { get; set; }
        public string exp { get; set; }
        public string closing_balance { get; set; }
        public string total { get; set; }
        public string pdf { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
