//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDelight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rest_registration
    {
        public int rest_id { get; set; }
        public string pid { get; set; }
        public string business_name { get; set; }
        public string business_type { get; set; }
        public string owner_name { get; set; }
        public string manager_name { get; set; }
        public string enqid { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string b_contact { get; set; }
        public string bo_contact { get; set; }
        public string location { get; set; }
        public string setup_cost { get; set; }
        public string var_code { get; set; }
        public string food { get; set; }
        public string total { get; set; }
        public string c_terms1 { get; set; }
        public string c_terms2 { get; set; }
        public string c_terms3 { get; set; }
        public string sms_package { get; set; }
        public System.DateTime creation_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime last_update { get; set; }
    }
}
