//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class brand_master
    {
        public int BrandId { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> NoOfLocations { get; set; }
        public Nullable<int> BrandManagerId { get; set; }
        public string PrimaryId { get; set; }
        public string BrandManagerName { get; set; }
    }
}
