//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        public int Id { get; set; }
        public Nullable<int> merchantId { get; set; }
        public string bankName { get; set; }
        public string bankBranch { get; set; }
        public string chequeNumber { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
