//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumergiftcardtransactiondetail
    {
        public int id { get; set; }
        public string RequestString { get; set; }
        public string SentRequestDetails { get; set; }
        public string ResponseTransactionId { get; set; }
        public string ResponseStatus { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
        public string ConsumerId { get; set; }
        public string MerchantId { get; set; }
        public Nullable<int> GiftCardId { get; set; }
        public Nullable<int> TransactionAmount { get; set; }
        public string securitySignature { get; set; }
    }
}
