//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public int currency_id { get; set; }
        public string country { get; set; }
        public string online_order { get; set; }
        public string gift_card { get; set; }
        public string symbol { get; set; }
        public string amount { get; set; }
    }
}
