//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftcardmaster
    {
        public int GiftCardId { get; set; }
        public string MerchantUserId { get; set; }
        public Nullable<int> Denomination1 { get; set; }
        public Nullable<int> Denomination2 { get; set; }
        public Nullable<int> Denomination3 { get; set; }
        public Nullable<int> Denomination4 { get; set; }
        public string Email { get; set; }
        public string TermsCondition { get; set; }
        public Nullable<System.DateTime> SetDate { get; set; }
        public byte[] Denom1DEC { get; set; }
        public byte[] Denom2DEC { get; set; }
        public byte[] Denom3DEC { get; set; }
        public byte[] Denom4DEC { get; set; }
    }
}
