//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class language_master
    {
        public int LanguageiId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Language { get; set; }
        public string LanguageCode { get; set; }
    }
}
