//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant_master
    {
        public int merchantid { get; set; }
        public string MerchantName { get; set; }
        public string BuildingName { get; set; }
        public string SocietyName { get; set; }
        public string Street { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> PinCode { get; set; }
        public byte[] MerchantLogo { get; set; }
        public Nullable<int> Category { get; set; }
        public string UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string DECName { get; set; }
        public byte[] MerchantDEC { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string user_type { get; set; }
        public string rm_email { get; set; }
        public string rname { get; set; }
        public string activation { get; set; }
        public string aproval { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string user_contact { get; set; }
        public string UserName { get; set; }
        public string last_name { get; set; }
        public string password { get; set; }
        public string merchantDecFromLibrary { get; set; }
        public string DECColor { get; set; }
        public byte[] MenuCsvFile { get; set; }
        public string VARCode { get; set; }
        public string button1_text { get; set; }
        public string button1_url { get; set; }
        public string button2_text { get; set; }
        public string button2_url { get; set; }
        public string button3_text { get; set; }
        public string button3_url { get; set; }
        public string button4_text { get; set; }
        public string button4_url { get; set; }
        public string pdf { get; set; }
        public Nullable<int> salesperson { get; set; }
        public Nullable<int> yearlysub { get; set; }
        public Nullable<int> sms { get; set; }
        public Nullable<int> onetime { get; set; }
        public Nullable<int> onlineper { get; set; }
        public Nullable<int> onlineord { get; set; }
        public Nullable<int> giftcard { get; set; }
        public Nullable<int> total { get; set; }
        public string paystatus { get; set; }
        public string transid { get; set; }
        public Nullable<int> gst { get; set; }
        public string bankName { get; set; }
        public string bankBranch { get; set; }
        public string chequeNumber { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<bool> RunRewardProgram { get; set; }
        public Nullable<int> cgst { get; set; }
        public Nullable<int> sgst { get; set; }
        public Nullable<int> NoOfLocations { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public Nullable<int> NoOfSMS { get; set; }
        public string RedeemProgram { get; set; }
        public string currency { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> GiftCardDiscount { get; set; }
        public Nullable<int> Taxes { get; set; }

        public Nullable<int> RewardRs { get; set; }
        public Nullable<int> RewardPoints { get; set; }
        public Nullable<int> RedeemPt { get; set; }
        public Nullable<int> RedeemRs { get; set; }
        public string RewardName { get; set; }
    }
}
