//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Consumer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consumer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsumerApp.Resources.Consumer", typeof(Consumer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Note: By entering your additional cell numbers, email ids, your DECs from those businesses that have these cell numbers, email ids will show up in the offertraker app. Enjoy your Global Digital Engagement Cards in one place now!.
        /// </summary>
        public static string AdditionalNosPrompt {
            get {
                return ResourceManager.GetString("AdditionalNosPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Merchant.
        /// </summary>
        public static string AddMerchant {
            get {
                return ResourceManager.GetString("AddMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary coupon.
        /// </summary>
        public static string AnniversaryCopupon {
            get {
                return ResourceManager.GetString("AnniversaryCopupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable In.
        /// </summary>
        public static string ApplicableIn {
            get {
                return ResourceManager.GetString("ApplicableIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As On DEC.
        /// </summary>
        public static string AsOnDEC {
            get {
                return ResourceManager.GetString("AsOnDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Benefits.
        /// </summary>
        public static string BankBenefits {
            get {
                return ResourceManager.GetString("BankBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        public static string BankDetails {
            get {
                return ResourceManager.GetString("BankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits of.
        /// </summary>
        public static string Benefitsof {
            get {
                return ResourceManager.GetString("Benefitsof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for Bill Amount.
        /// </summary>
        public static string BillValidationMessage {
            get {
                return ResourceManager.GetString("BillValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday coupon.
        /// </summary>
        public static string BirthdayCoupon {
            get {
                return ResourceManager.GetString("BirthdayCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Mobile No.
        /// </summary>
        public static string BusinessMobileNo {
            get {
                return ResourceManager.GetString("BusinessMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy and Share gift cards.
        /// </summary>
        public static string BuyAndShareGiftCards {
            get {
                return ResourceManager.GetString("BuyAndShareGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Gift Cards.
        /// </summary>
        public static string BuyGiftCards {
            get {
                return ResourceManager.GetString("BuyGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Country.
        /// </summary>
        public static string ChangeCountry {
            get {
                return ResourceManager.GetString("ChangeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Saved..
        /// </summary>
        public static string CommentSaved {
            get {
                return ResourceManager.GetString("CommentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer.
        /// </summary>
        public static string consumer {
            get {
                return ResourceManager.GetString("consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Cell.
        /// </summary>
        public static string ConsumerCell {
            get {
                return ResourceManager.GetString("ConsumerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer&apos;s Email.
        /// </summary>
        public static string ConsumerEmail {
            get {
                return ResourceManager.GetString("ConsumerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Login.
        /// </summary>
        public static string ConsumerLogin {
            get {
                return ResourceManager.GetString("ConsumerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Updated.
        /// </summary>
        public static string ConsumerUpdated {
            get {
                return ResourceManager.GetString("ConsumerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Background.
        /// </summary>
        public static string CopuponBackground {
            get {
                return ResourceManager.GetString("CopuponBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Preferences Updated.
        /// </summary>
        public static string CountryUpdated {
            get {
                return ResourceManager.GetString("CountryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Description.
        /// </summary>
        public static string CouponDescription {
            get {
                return ResourceManager.GetString("CouponDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Details.
        /// </summary>
        public static string CouponDetails {
            get {
                return ResourceManager.GetString("CouponDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon list.
        /// </summary>
        public static string CouponList {
            get {
                return ResourceManager.GetString("CouponList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        public static string Coupons {
            get {
                return ResourceManager.GetString("Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Title.
        /// </summary>
        public static string CouponTitle {
            get {
                return ResourceManager.GetString("CouponTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bank.
        /// </summary>
        public static string CreateBank {
            get {
                return ResourceManager.GetString("CreateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Coupons.
        /// </summary>
        public static string CreateCoupons {
            get {
                return ResourceManager.GetString("CreateCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Review.
        /// </summary>
        public static string CreateReview {
            get {
                return ResourceManager.GetString("CreateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support numbers:.
        /// </summary>
        public static string CustomerSupport {
            get {
                return ResourceManager.GetString("CustomerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Anniversary.
        /// </summary>
        public static string DateOfAnniversary {
            get {
                return ResourceManager.GetString("DateOfAnniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC Background.
        /// </summary>
        public static string DECBackground {
            get {
                return ResourceManager.GetString("DECBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC Name.
        /// </summary>
        public static string DECName {
            get {
                return ResourceManager.GetString("DECName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC share.
        /// </summary>
        public static string DECShare {
            get {
                return ResourceManager.GetString("DECShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for Discount.
        /// </summary>
        public static string DiscountValidationMessage {
            get {
                return ResourceManager.GetString("DiscountValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bank.
        /// </summary>
        public static string EditBank {
            get {
                return ResourceManager.GetString("EditBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Merchant.
        /// </summary>
        public static string EditMerchant {
            get {
                return ResourceManager.GetString("EditMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Email Id.
        /// </summary>
        public static string EmailValidationMessage {
            get {
                return ResourceManager.GetString("EmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bill Amount.
        /// </summary>
        public static string EnterBillAmount {
            get {
                return ResourceManager.GetString("EnterBillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your registered phone number / Email..
        /// </summary>
        public static string ForgotPasswordCaption {
            get {
                return ResourceManager.GetString("ForgotPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your phone SMS to reset your password.
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your mail box to reset your password.
        /// </summary>
        public static string ForgotPasswordMessage1 {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving bank list.
        /// </summary>
        public static string GetAllException {
            get {
                return ResourceManager.GetString("GetAllException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving reviews.
        /// </summary>
        public static string GetAllReviewsException {
            get {
                return ResourceManager.GetString("GetAllReviewsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving bank dec details.
        /// </summary>
        public static string GetBankDECException {
            get {
                return ResourceManager.GetString("GetBankDECException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving business category list.
        /// </summary>
        public static string GetCategoriesException {
            get {
                return ResourceManager.GetString("GetCategoriesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving city list from state.
        /// </summary>
        public static string GetCityListException {
            get {
                return ResourceManager.GetString("GetCityListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving consumer details.
        /// </summary>
        public static string GetConsumerByIdException {
            get {
                return ResourceManager.GetString("GetConsumerByIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving consumer logo.
        /// </summary>
        public static string GetConsumerLogoException {
            get {
                return ResourceManager.GetString("GetConsumerLogoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while calculating consumer points.
        /// </summary>
        public static string GetConsumerPointsException {
            get {
                return ResourceManager.GetString("GetConsumerPointsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving country code.
        /// </summary>
        public static string GetCountryCodeException {
            get {
                return ResourceManager.GetString("GetCountryCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving country list.
        /// </summary>
        public static string GetCountryListException {
            get {
                return ResourceManager.GetString("GetCountryListException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving coupon conditions.
        /// </summary>
        public static string GetCouponCondtiongsException {
            get {
                return ResourceManager.GetString("GetCouponCondtiongsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving coupon details.
        /// </summary>
        public static string GetCouponDetails {
            get {
                return ResourceManager.GetString("GetCouponDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving coupons.
        /// </summary>
        public static string GetCouponsException {
            get {
                return ResourceManager.GetString("GetCouponsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving event conditions.
        /// </summary>
        public static string GetEventCondtiongsException {
            get {
                return ResourceManager.GetString("GetEventCondtiongsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving gift card denominations.
        /// </summary>
        public static string GetGiftCardDenominationException {
            get {
                return ResourceManager.GetString("GetGiftCardDenominationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving language details.
        /// </summary>
        public static string GetLanguageException {
            get {
                return ResourceManager.GetString("GetLanguageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving location list from city.
        /// </summary>
        public static string GetLocationsException {
            get {
                return ResourceManager.GetString("GetLocationsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving merchant dec details.
        /// </summary>
        public static string GetMerchantDECException {
            get {
                return ResourceManager.GetString("GetMerchantDECException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving merchant details.
        /// </summary>
        public static string GetMerchantDetails {
            get {
                return ResourceManager.GetString("GetMerchantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving merchant list.
        /// </summary>
        public static string GetMerchantsException {
            get {
                return ResourceManager.GetString("GetMerchantsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get New DEC.
        /// </summary>
        public static string GetNewDEC {
            get {
                return ResourceManager.GetString("GetNewDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving pending reviews.
        /// </summary>
        public static string GetPendingReviewsException {
            get {
                return ResourceManager.GetString("GetPendingReviewsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving state list from country.
        /// </summary>
        public static string GetStatesException {
            get {
                return ResourceManager.GetString("GetStatesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        public static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Consumer.
        /// </summary>
        public static string InvalidConsumer {
            get {
                return ResourceManager.GetString("InvalidConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Consumer review.
        /// </summary>
        public static string InvalidConsumerreview {
            get {
                return ResourceManager.GetString("InvalidConsumerreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant with mobile no xxx does not exist..
        /// </summary>
        public static string InvalidMerchantErrorMessage {
            get {
                return ResourceManager.GetString("InvalidMerchantErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is invalid..
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Favourites.
        /// </summary>
        public static string LocalFavourites {
            get {
                return ResourceManager.GetString("LocalFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Discount.
        /// </summary>
        public static string MaxDiscount {
            get {
                return ResourceManager.GetString("MaxDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Details.
        /// </summary>
        public static string MerchantDetails {
            get {
                return ResourceManager.GetString("MerchantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant List.
        /// </summary>
        public static string MerchantList {
            get {
                return ResourceManager.GetString("MerchantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        public static string MobileNumberPrompt {
            get {
                return ResourceManager.GetString("MobileNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My cards.
        /// </summary>
        public static string MyCards {
            get {
                return ResourceManager.GetString("MyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Coupons.
        /// </summary>
        public static string MyCoupons {
            get {
                return ResourceManager.GetString("MyCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Digital Cards.
        /// </summary>
        public static string MyDigitalCards {
            get {
                return ResourceManager.GetString("MyDigitalCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Me.
        /// </summary>
        public static string NearMe {
            get {
                return ResourceManager.GetString("NearMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coupons are shared with you by this merchant!.
        /// </summary>
        public static string NoCouponsPrompt {
            get {
                return ResourceManager.GetString("NoCouponsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The merchant has not set any gift cards yet..
        /// </summary>
        public static string NoGiftCardsPrompt {
            get {
                return ResourceManager.GetString("NoGiftCardsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gift cards purchased by you..
        /// </summary>
        public static string NoGiftCardsPurchasedPrompt {
            get {
                return ResourceManager.GetString("NoGiftCardsPurchasedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers near me.
        /// </summary>
        public static string OffersNearMe {
            get {
                return ResourceManager.GetString("OffersNearMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number (optional).
        /// </summary>
        public static string OptionalMobileNumber {
            get {
                return ResourceManager.GetString("OptionalMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you an OTP on the new email id entered by you. Please enter it here to confirm the change:.
        /// </summary>
        public static string OTPEmailMessage {
            get {
                return ResourceManager.GetString("OTPEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to send OTP to email id xxx. Please try again later..
        /// </summary>
        public static string OTPErrorMessage1 {
            get {
                return ResourceManager.GetString("OTPErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to generate OTP. Please try again later..
        /// </summary>
        public static string OTPErrorMessage2 {
            get {
                return ResourceManager.GetString("OTPErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to send OTP on cell number nnn. Please try again later..
        /// </summary>
        public static string OTPErrorMessage3 {
            get {
                return ResourceManager.GetString("OTPErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you an OTP on the new phone number entered by you. Please enter it here to confirm the change:.
        /// </summary>
        public static string OTPPhoneMessage {
            get {
                return ResourceManager.GetString("OTPPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Verified.
        /// </summary>
        public static string OTPVerified {
            get {
                return ResourceManager.GetString("OTPVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Email.
        /// </summary>
        public static string OwnerEmail {
            get {
                return ResourceManager.GetString("OwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Min 4 Characters).
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reviews.
        /// </summary>
        public static string PendingReviews {
            get {
                return ResourceManager.GetString("PendingReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Off.
        /// </summary>
        public static string PercentageOff {
            get {
                return ResourceManager.GetString("PercentageOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for % Off.
        /// </summary>
        public static string PercentOffValidationMessage {
            get {
                return ResourceManager.GetString("PercentOffValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write a phone number.
        /// </summary>
        public static string PhoneValidationMessage {
            get {
                return ResourceManager.GetString("PhoneValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture as displayed on Digital Card:.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write a pin code.
        /// </summary>
        public static string PinCodeValidationMessage {
            get {
                return ResourceManager.GetString("PinCodeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privilege program.
        /// </summary>
        public static string privilegeprogram {
            get {
                return ResourceManager.GetString("privilegeprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        public static string Redeem {
            get {
                return ResourceManager.GetString("Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redeem code.
        /// </summary>
        public static string RedeemCode {
            get {
                return ResourceManager.GetString("RedeemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this QR Code at the business to redeem the coupon.
        /// </summary>
        public static string RedeemCouponPrompt {
            get {
                return ResourceManager.GetString("RedeemCouponPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string RegionalSetting {
            get {
                return ResourceManager.GetString("RegionalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to register Consumer.
        /// </summary>
        public static string RegisterConsumerError {
            get {
                return ResourceManager.GetString("RegisterConsumerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Email Id.
        /// </summary>
        public static string RegisteredEmailId {
            get {
                return ResourceManager.GetString("RegisteredEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Mobile Number.
        /// </summary>
        public static string RegisteredMobileNumber {
            get {
                return ResourceManager.GetString("RegisteredMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new merchant.
        /// </summary>
        public static string Registernewmerchant {
            get {
                return ResourceManager.GetString("Registernewmerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string ResetMessage {
            get {
                return ResourceManager.GetString("ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Resetpassword {
            get {
                return ResourceManager.GetString("Resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string Resetyourpassword {
            get {
                return ResourceManager.GetString("Resetyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Submission.
        /// </summary>
        public static string ReviewSubmission {
            get {
                return ResourceManager.GetString("ReviewSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Points:.
        /// </summary>
        public static string RewardPoints {
            get {
                return ResourceManager.GetString("RewardPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while saving consumer review comment.
        /// </summary>
        public static string SaveCommentException {
            get {
                return ResourceManager.GetString("SaveCommentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card Payment Successfully.
        /// </summary>
        public static string SaveGiftCard {
            get {
                return ResourceManager.GetString("SaveGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while saving gift card.
        /// </summary>
        public static string SaveGiftCardException {
            get {
                return ResourceManager.GetString("SaveGiftCardException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while submitting review by Consumer..
        /// </summary>
        public static string SaveReviewException {
            get {
                return ResourceManager.GetString("SaveReviewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Coupon.
        /// </summary>
        public static string ScanCoupon {
            get {
                return ResourceManager.GetString("ScanCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Business Category.
        /// </summary>
        public static string SelectBusinessCategory {
            get {
                return ResourceManager.GetString("SelectBusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Locality.
        /// </summary>
        public static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Sent Successfully to selected contacts..
        /// </summary>
        public static string SendCouponToFriends {
            get {
                return ResourceManager.GetString("SendCouponToFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DEC.
        /// </summary>
        public static string SendDEC {
            get {
                return ResourceManager.GetString("SendDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC Sent Successfully to selected contacts..
        /// </summary>
        public static string SendDECToFriends {
            get {
                return ResourceManager.GetString("SendDECToFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while sending OTP over email.
        /// </summary>
        public static string SendOTPException {
            get {
                return ResourceManager.GetString("SendOTPException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while sending OTP to phone.
        /// </summary>
        public static string SendOTPException1 {
            get {
                return ResourceManager.GetString("SendOTPException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while sending OTP to phone 3.
        /// </summary>
        public static string SendOTPException2 {
            get {
                return ResourceManager.GetString("SendOTPException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent successfully.
        /// </summary>
        public static string SendOTPMessage {
            get {
                return ResourceManager.GetString("SendOTPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS / Email.
        /// </summary>
        public static string SendSMSEmail {
            get {
                return ResourceManager.GetString("SendSMSEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set coupons for events.
        /// </summary>
        public static string SetCouponForEvents {
            get {
                return ResourceManager.GetString("SetCouponForEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set coupons.
        /// </summary>
        public static string SetCoupons {
            get {
                return ResourceManager.GetString("SetCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the following dates to allow businesses to send you offers.
        /// </summary>
        public static string SetDatePrompt {
            get {
                return ResourceManager.GetString("SetDatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gift cards.
        /// </summary>
        public static string SetGiftCards {
            get {
                return ResourceManager.GetString("SetGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Review questions.
        /// </summary>
        public static string SetReviewQuestions {
            get {
                return ResourceManager.GetString("SetReviewQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while share coupon with consumer.
        /// </summary>
        public static string ShareCouponException {
            get {
                return ResourceManager.GetString("ShareCouponException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon shared with consumer Successfully..
        /// </summary>
        public static string ShareCouponMessage {
            get {
                return ResourceManager.GetString("ShareCouponMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Coupon with friends.
        /// </summary>
        public static string ShareCouponWithFriends {
            get {
                return ResourceManager.GetString("ShareCouponWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while share dec with consumer.
        /// </summary>
        public static string ShareDECException {
            get {
                return ResourceManager.GetString("ShareDECException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC Shared successfully..
        /// </summary>
        public static string ShareDECMessage {
            get {
                return ResourceManager.GetString("ShareDECMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Gift Cards.
        /// </summary>
        public static string ShareGiftCards {
            get {
                return ResourceManager.GetString("ShareGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Gift Card with Friends.
        /// </summary>
        public static string ShareGiftCardwithFriends {
            get {
                return ResourceManager.GetString("ShareGiftCardwithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share merchant&apos;s DEC with friends.
        /// </summary>
        public static string ShareWithFriends {
            get {
                return ResourceManager.GetString("ShareWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society Name.
        /// </summary>
        public static string SocietyName {
            get {
                return ResourceManager.GetString("SocietyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Marketing Platform.
        /// </summary>
        public static string SplashScreenHeading {
            get {
                return ResourceManager.GetString("SplashScreenHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all your Digital Cards, coupons, gift cards in one place. Enjoy the convenience of ordering from your Digital Cards..
        /// </summary>
        public static string SplashScreenText {
            get {
                return ResourceManager.GetString("SplashScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Comment.
        /// </summary>
        public static string SubmitComment {
            get {
                return ResourceManager.GetString("SubmitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string SubmitReview {
            get {
                return ResourceManager.GetString("SubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your valuable feedback within the next 24 hours and win a coupon.
        /// </summary>
        public static string SubmitReviewPrompt {
            get {
                return ResourceManager.GetString("SubmitReviewPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr./Mrs. Name.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while updating consumer.
        /// </summary>
        public static string UpdateConsumerException {
            get {
                return ResourceManager.GetString("UpdateConsumerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while updating country.
        /// </summary>
        public static string UpdateCountryException {
            get {
                return ResourceManager.GetString("UpdateCountryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name (Mobile Number/Email).
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid above bill amount.
        /// </summary>
        public static string ValidAbove {
            get {
                return ResourceManager.GetString("ValidAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid At.
        /// </summary>
        public static string ValidAt {
            get {
                return ResourceManager.GetString("ValidAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Till.
        /// </summary>
        public static string ValidTill {
            get {
                return ResourceManager.GetString("ValidTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Email.
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while verifying email OTP.
        /// </summary>
        public static string VerifyOTPException {
            get {
                return ResourceManager.GetString("VerifyOTPException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while verifying phone2 OTP.
        /// </summary>
        public static string VerifyOTPException1 {
            get {
                return ResourceManager.GetString("VerifyOTPException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while verifying phone3 otp.
        /// </summary>
        public static string VerifyOTPException2 {
            get {
                return ResourceManager.GetString("VerifyOTPException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View / Edit Coupons.
        /// </summary>
        public static string ViewEditCoupons {
            get {
                return ResourceManager.GetString("ViewEditCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Gift Cards.
        /// </summary>
        public static string ViewGiftCards {
            get {
                return ResourceManager.GetString("ViewGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferTraker!.
        /// </summary>
        public static string WelcomePrompt {
            get {
                return ResourceManager.GetString("WelcomePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mobile No.
        /// </summary>
        public static string YourMobileNo {
            get {
                return ResourceManager.GetString("YourMobileNo", resourceCulture);
            }
        }
    }
}
