//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstaDelight {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstaDelight() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaDelight.Resources.InstaDelight", typeof(InstaDelight).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Account.
        /// </summary>
        public static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Merchant.
        /// </summary>
        public static string AddMerchant {
            get {
                return ResourceManager.GetString("AddMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New VAR Code.
        /// </summary>
        public static string AddNewVARCode {
            get {
                return ResourceManager.GetString("AddNewVARCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Login.
        /// </summary>
        public static string AdminLogin {
            get {
                return ResourceManager.GetString("AdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary coupon.
        /// </summary>
        public static string AnniversaryCopupon {
            get {
                return ResourceManager.GetString("AnniversaryCopupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As On DEC.
        /// </summary>
        public static string AsOnDEC {
            get {
                return ResourceManager.GetString("AsOnDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        public static string BankDetails {
            get {
                return ResourceManager.GetString("BankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank List.
        /// </summary>
        public static string BankList {
            get {
                return ResourceManager.GetString("BankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for Bill Amount.
        /// </summary>
        public static string BillValidationMessage {
            get {
                return ResourceManager.GetString("BillValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday coupon.
        /// </summary>
        public static string BirthdayCoupon {
            get {
                return ResourceManager.GetString("BirthdayCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz Name.
        /// </summary>
        public static string BizName {
            get {
                return ResourceManager.GetString("BizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        public static string BusinessCategory {
            get {
                return ResourceManager.GetString("BusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy and Share gift cards.
        /// </summary>
        public static string BuyAndShareGiftCards {
            get {
                return ResourceManager.GetString("BuyAndShareGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer.
        /// </summary>
        public static string Consumer {
            get {
                return ResourceManager.GetString("Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Cell.
        /// </summary>
        public static string ConsumerCell {
            get {
                return ResourceManager.GetString("ConsumerCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Consumers.
        /// </summary>
        public static string ConsumetCount {
            get {
                return ResourceManager.GetString("ConsumetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Background.
        /// </summary>
        public static string CopuponBackground {
            get {
                return ResourceManager.GetString("CopuponBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Description.
        /// </summary>
        public static string CouponDescription {
            get {
                return ResourceManager.GetString("CouponDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Details.
        /// </summary>
        public static string CouponDetails {
            get {
                return ResourceManager.GetString("CouponDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon list.
        /// </summary>
        public static string CouponList {
            get {
                return ResourceManager.GetString("CouponList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        public static string Coupons {
            get {
                return ResourceManager.GetString("Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Title.
        /// </summary>
        public static string CouponTitle {
            get {
                return ResourceManager.GetString("CouponTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bank.
        /// </summary>
        public static string CreateBank {
            get {
                return ResourceManager.GetString("CreateBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Coupons.
        /// </summary>
        public static string CreateCoupons {
            get {
                return ResourceManager.GetString("CreateCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Review.
        /// </summary>
        public static string CreateReview {
            get {
                return ResourceManager.GetString("CreateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create VAR.
        /// </summary>
        public static string CreateVAR {
            get {
                return ResourceManager.GetString("CreateVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offertraker Customer Support.
        /// </summary>
        public static string CustomerSupport {
            get {
                return ResourceManager.GetString("CustomerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Anniversary.
        /// </summary>
        public static string DateOfAnniversary {
            get {
                return ResourceManager.GetString("DateOfAnniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC Background.
        /// </summary>
        public static string DECBackground {
            get {
                return ResourceManager.GetString("DECBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC Name.
        /// </summary>
        public static string DECName {
            get {
                return ResourceManager.GetString("DECName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC share.
        /// </summary>
        public static string DECShare {
            get {
                return ResourceManager.GetString("DECShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for Discount.
        /// </summary>
        public static string DiscountValidationMessage {
            get {
                return ResourceManager.GetString("DiscountValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Sample File.
        /// </summary>
        public static string DownloadSampleFile {
            get {
                return ResourceManager.GetString("DownloadSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bank.
        /// </summary>
        public static string EditBank {
            get {
                return ResourceManager.GetString("EditBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Merchant.
        /// </summary>
        public static string EditMerchant {
            get {
                return ResourceManager.GetString("EditMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit VAR.
        /// </summary>
        public static string EditVAR {
            get {
                return ResourceManager.GetString("EditVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Email Id.
        /// </summary>
        public static string EmailValidationMessage {
            get {
                return ResourceManager.GetString("EmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bill Amount.
        /// </summary>
        public static string EnterBillAmount {
            get {
                return ResourceManager.GetString("EnterBillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Results.
        /// </summary>
        public static string ExportResults {
            get {
                return ResourceManager.GetString("ExportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your registered phone number / Email..
        /// </summary>
        public static string ForgotPasswordCaption {
            get {
                return ResourceManager.GetString("ForgotPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your phone SMS to reset your password.
        /// </summary>
        public static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your mail box to reset your password.
        /// </summary>
        public static string ForgotPasswordMessage1 {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving country code.
        /// </summary>
        public static string GetCountryCodeException {
            get {
                return ResourceManager.GetString("GetCountryCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image from gallery.
        /// </summary>
        public static string ImageGalleryHeading {
            get {
                return ResourceManager.GetString("ImageGalleryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Bonus Points.
        /// </summary>
        public static string JoiningBonus {
            get {
                return ResourceManager.GetString("JoiningBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDG Report.
        /// </summary>
        public static string LDGReport {
            get {
                return ResourceManager.GetString("LDGReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Bank with Consumer.
        /// </summary>
        public static string LinkBankWithConsumer {
            get {
                return ResourceManager.GetString("LinkBankWithConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Favourites.
        /// </summary>
        public static string LocalFavourites {
            get {
                return ResourceManager.GetString("LocalFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Discount.
        /// </summary>
        public static string MaxDiscount {
            get {
                return ResourceManager.GetString("MaxDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string Merchant {
            get {
                return ResourceManager.GetString("Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Details.
        /// </summary>
        public static string MerchantDetails {
            get {
                return ResourceManager.GetString("MerchantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant List.
        /// </summary>
        public static string MerchantList {
            get {
                return ResourceManager.GetString("MerchantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My cards.
        /// </summary>
        public static string MyCards {
            get {
                return ResourceManager.GetString("MyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Digital Cards.
        /// </summary>
        public static string MyDigitalCards {
            get {
                return ResourceManager.GetString("MyDigitalCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers near me.
        /// </summary>
        public static string OffersNearMe {
            get {
                return ResourceManager.GetString("OffersNearMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number (optional).
        /// </summary>
        public static string OptionalMobileNumber {
            get {
                return ResourceManager.GetString("OptionalMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s Email.
        /// </summary>
        public static string OwnerEmail {
            get {
                return ResourceManager.GetString("OwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Min 6 Characters).
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reviews.
        /// </summary>
        public static string PendingReviews {
            get {
                return ResourceManager.GetString("PendingReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Off.
        /// </summary>
        public static string PercentageOff {
            get {
                return ResourceManager.GetString("PercentageOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for % Off.
        /// </summary>
        public static string PercentOffValidationMessage {
            get {
                return ResourceManager.GetString("PercentOffValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write a phone number.
        /// </summary>
        public static string PhoneValidationMessage {
            get {
                return ResourceManager.GetString("PhoneValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write a pin code.
        /// </summary>
        public static string PinCodeValidationMessage {
            get {
                return ResourceManager.GetString("PinCodeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Email or Phone as your primary login.
        /// </summary>
        public static string PrimaryLoginPrompt {
            get {
                return ResourceManager.GetString("PrimaryLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Primary ID for Login.
        /// </summary>
        public static string PrimeryIDLogin {
            get {
                return ResourceManager.GetString("PrimeryIDLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        public static string Redeem {
            get {
                return ResourceManager.GetString("Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redeem code.
        /// </summary>
        public static string RedeemCode {
            get {
                return ResourceManager.GetString("RedeemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Formula.
        /// </summary>
        public static string RedeemFormula {
            get {
                return ResourceManager.GetString("RedeemFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem options for points.
        /// </summary>
        public static string RedeemOptions {
            get {
                return ResourceManager.GetString("RedeemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string RegionalSetting {
            get {
                return ResourceManager.GetString("RegionalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Mobile Number.
        /// </summary>
        public static string RegisteredMobileNumber {
            get {
                return ResourceManager.GetString("RegisteredMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new merchant.
        /// </summary>
        public static string Registernewmerchant {
            get {
                return ResourceManager.GetString("Registernewmerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string ResetMessage {
            get {
                return ResourceManager.GetString("ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Resetpassword {
            get {
                return ResourceManager.GetString("Resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string Resetyourpassword {
            get {
                return ResourceManager.GetString("Resetyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Submission.
        /// </summary>
        public static string ReviewSubmission {
            get {
                return ResourceManager.GetString("ReviewSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Formula.
        /// </summary>
        public static string RewardFormula {
            get {
                return ResourceManager.GetString("RewardFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to run a reward program.
        /// </summary>
        public static string RewardProgramPrompt {
            get {
                return ResourceManager.GetString("RewardProgramPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward/Redeem Formula.
        /// </summary>
        public static string RewardRedeemFormula {
            get {
                return ResourceManager.GetString("RewardRedeemFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rupees.
        /// </summary>
        public static string Rupees {
            get {
                return ResourceManager.GetString("Rupees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rep.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Coupon.
        /// </summary>
        public static string ScanCoupon {
            get {
                return ResourceManager.GetString("ScanCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSV File.
        /// </summary>
        public static string SelectCSVFile {
            get {
                return ResourceManager.GetString("SelectCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select From Library.
        /// </summary>
        public static string SelectFromLibrary {
            get {
                return ResourceManager.GetString("SelectFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Search Parameters.
        /// </summary>
        public static string SelectSearchParameters {
            get {
                return ResourceManager.GetString("SelectSearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select to edit).
        /// </summary>
        public static string Selecttoedit {
            get {
                return ResourceManager.GetString("Selecttoedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select VAR Code.
        /// </summary>
        public static string SelectVARCode {
            get {
                return ResourceManager.GetString("SelectVARCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DEC.
        /// </summary>
        public static string SendDEC {
            get {
                return ResourceManager.GetString("SendDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS / Email.
        /// </summary>
        public static string SendSMSEmail {
            get {
                return ResourceManager.GetString("SendSMSEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DEC to list of consumers.
        /// </summary>
        public static string SendToConsumerList {
            get {
                return ResourceManager.GetString("SendToConsumerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Button URLs.
        /// </summary>
        public static string SetButtonURL {
            get {
                return ResourceManager.GetString("SetButtonURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set coupons for events.
        /// </summary>
        public static string SetCouponForEvents {
            get {
                return ResourceManager.GetString("SetCouponForEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set coupons.
        /// </summary>
        public static string SetCoupons {
            get {
                return ResourceManager.GetString("SetCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gift cards.
        /// </summary>
        public static string SetGiftCards {
            get {
                return ResourceManager.GetString("SetGiftCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Image.
        /// </summary>
        public static string SetImage {
            get {
                return ResourceManager.GetString("SetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this image as Digital Card background.
        /// </summary>
        public static string SetImageHeading {
            get {
                return ResourceManager.GetString("SetImageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Review questions.
        /// </summary>
        public static string SetReviewQuestions {
            get {
                return ResourceManager.GetString("SetReviewQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share our DEC with friends.
        /// </summary>
        public static string ShareWithFriends {
            get {
                return ResourceManager.GetString("ShareWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Balance.
        /// </summary>
        public static string SMSBalance {
            get {
                return ResourceManager.GetString("SMSBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Sent.
        /// </summary>
        public static string SMSSent {
            get {
                return ResourceManager.GetString("SMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society Name.
        /// </summary>
        public static string SocietyName {
            get {
                return ResourceManager.GetString("SocietyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr. No..
        /// </summary>
        public static string SrNo {
            get {
                return ResourceManager.GetString("SrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string SubmitReview {
            get {
                return ResourceManager.GetString("SubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Account.
        /// </summary>
        public static string SuspendAccount {
            get {
                return ResourceManager.GetString("SuspendAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name (Mobile Number/Email).
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid above bill amount.
        /// </summary>
        public static string ValidAbove {
            get {
                return ResourceManager.GetString("ValidAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid At.
        /// </summary>
        public static string ValidAt {
            get {
                return ResourceManager.GetString("ValidAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Till.
        /// </summary>
        public static string ValidTill {
            get {
                return ResourceManager.GetString("ValidTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR Code.
        /// </summary>
        public static string VARCode {
            get {
                return ResourceManager.GetString("VARCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR List.
        /// </summary>
        public static string VARList {
            get {
                return ResourceManager.GetString("VARList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the VAR (Company Name).
        /// </summary>
        public static string VARName {
            get {
                return ResourceManager.GetString("VARName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s/Manager&apos;s Name.
        /// </summary>
        public static string VAROwner {
            get {
                return ResourceManager.GetString("VAROwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View / Edit Coupons.
        /// </summary>
        public static string ViewEditCoupons {
            get {
                return ResourceManager.GetString("ViewEditCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Registered Business.
        /// </summary>
        public static string ViewRegisteredBusiness {
            get {
                return ResourceManager.GetString("ViewRegisteredBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Offertraker.
        /// </summary>
        public static string WelcomePrompt {
            get {
                return ResourceManager.GetString("WelcomePrompt", resourceCulture);
            }
        }
    }
}
