using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MerchantApp.Models;
using System.Web.Mvc;

namespace MerchantApp
{
    public class GenerateCouponCode : Controller
    {
        
        public string CreateCouponCode(int merchantid)
        {
            string couponCode = "OTA001";
            /*Coupon Code should be autogenerated as OTA<3 digits>.
              Once we reach OTA999, the code should start the series OTB<3 digits>.
                Then once we reach OTB999, it should start the series OTC<3 digits>.
                Once we reach OTZ999, we can start again with OTA<3 digits>.
                This logic applies to each business. So each business will have the first coupon code as OTA001.
            */
            //First coupon
            using (MerchantEntities dataContext = new MerchantEntities())
            {
                int cpncnt = dataContext.coupons_master.Where(x => x.MerchantId == merchantid).Count();
                if (cpncnt == 0)
                {
                    couponCode = "OTA001";
                }
                else
                {
                    string lastcouponcode = dataContext.coupons_master.Where(x => x.MerchantId == merchantid).OrderByDescending(x => x.couponid).FirstOrDefault().CouponCode;

                    string initial = "OT";
                    string series = lastcouponcode.Substring(2, 1);
                    string number = lastcouponcode.Substring(3);
                    if (Convert.ToInt32(number) < 999)
                    {
                        int nextno = Convert.ToInt32(number) + 1;
                        couponCode = initial + series + nextno.ToString().PadLeft(3, '0');
                    }
                    else
                    {
                        char letter = Convert.ToChar(series);
                        char nextchar = ' ';
                        if (letter == 'Z')
                            nextchar = 'A';
                        else
                            nextchar = (char)(((int)letter) + 1);

                        couponCode = initial + nextchar + "001";
                    }
                }
            }
            return couponCode;

        }
    }
}