//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int branch_id { get; set; }
        public int referal_id { get; set; }
        public string restaurant_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public int veg { get; set; }
        public int nonveg { get; set; }
        public string online_payment { get; set; }
        public string cod { get; set; }
        public int minimun_order { get; set; }
        public System.TimeSpan opening_time { get; set; }
        public System.TimeSpan closing_time { get; set; }
        public string omcontact { get; set; }
        public string omemail { get; set; }
        public string omanager { get; set; }
        public string bmanager { get; set; }
        public string city { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public int confirmation { get; set; }
        public int approval { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime expire_date { get; set; }
        public System.DateTime last_update { get; set; }
        public int a { get; set; }
        public int b { get; set; }
        public int c { get; set; }
    }
}
