//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashbackdetail
    {
        public int Id { get; set; }
        public string MerchantId { get; set; }
        public Nullable<int> RedeemPoint { get; set; }
        public Nullable<int> RedeemRs { get; set; }
        public Nullable<int> FixedCashBack { get; set; }
        public Nullable<bool> IsCashBackPerTransaction { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
