//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expiryperiodmaster
    {
        public int Id { get; set; }
        public Nullable<int> expperiod { get; set; }
        public string expunit { get; set; }
        public string DisplayText { get; set; }
    }
}
