//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class help
    {
        public int help_id { get; set; }
        public string help_name { get; set; }
        public string help_file { get; set; }
        public System.DateTime creation_date { get; set; }
        public string deleted { get; set; }
    }
}
