//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchant_benefits
    {
        public int Id { get; set; }
        public string MerchantId { get; set; }
        public string Benefit1 { get; set; }
        public string Benefit2 { get; set; }
        public string Benefit3 { get; set; }
        public string Benefit4 { get; set; }
        public string Benefit5 { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
