//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public int PackageId { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string PackageName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<System.DateTime> Valid { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
