//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal
    {
        public int rest_id { get; set; }
        public string pid { get; set; }
        public string business_name { get; set; }
        public string business_type { get; set; }
        public string mrs { get; set; }
        public string owner_name { get; set; }
        public string owner_last_name { get; set; }
        public string post { get; set; }
        public string manager_name { get; set; }
        public string enqid { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string b_contact { get; set; }
        public string bo_contact { get; set; }
        public string location { get; set; }
        public string setup_cost { get; set; }
        public string var_code { get; set; }
        public string var { get; set; }
        public string food { get; set; }
        public string total { get; set; }
        public string c_terms1 { get; set; }
        public string c_terms2 { get; set; }
        public string c_terms3 { get; set; }
        public string sms_package { get; set; }
        public string sms_amount { get; set; }
        public System.DateTime creation_date { get; set; }
        public string created_by { get; set; }
        public string user_id { get; set; }
        public string user_email { get; set; }
        public string status { get; set; }
        public string user_comment { get; set; }
        public string admin_comment { get; set; }
        public string coupon_name { get; set; }
        public int coupon_per { get; set; }
        public string coupon_on { get; set; }
        public System.DateTime coupon_start { get; set; }
        public System.DateTime coupon_end { get; set; }
        public string coupon_location { get; set; }
        public string coupon_bank { get; set; }
        public string pdf { get; set; }
        public string deleted { get; set; }
        public System.DateTime last_update { get; set; }
    }
}
