//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sales_id { get; set; }
        public string sales_name { get; set; }
        public string sales_lastname { get; set; }
        public string sales_username { get; set; }
        public string sales_email { get; set; }
        public string sales_password { get; set; }
        public string sales_contact { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
