//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_master
    {
        public int StaffId { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string StaffName { get; set; }
        public string PrimaryId { get; set; }
        public Nullable<bool> IsCouponSendAllowed { get; set; }
        public Nullable<int> StaffMasterId { get; set; }
    }
}
